# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python package

on:
  push:
    branches: [ master ]
    paths:
      - 'python/**'
      - .github/workflows/python.yml
  pull_request:
    branches: [ master ]
    paths:
      - 'python/**'

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.7', '3.8', '3.9']

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install black nose
        cd python; pip install -r requirements.txt
    - name: Reformat
      run: |
        cd python; black --check .
    - name: Run tests
      run: |
        cd python; nosetests
